// resources/js/Pages/Welcome.jsx
import { Head, Link } from '@inertiajs/react';

export default function Welcome({ auth, laravelVersion, phpVersion }) {
    return (
        <>
            <Head title="Welcome" />
            <div className="min-h-screen" style={{ backgroundColor: '#0A1017' }}>
                <div className="relative">
                    {/* Navigation */}
                    <nav className="p-6 flex justify-end">
                        {auth.user && (
                            <Link
                                href={route('dashboard')}
                                className="text-white hover:text-gray-300 px-4 py-2 rounded-md transition"
                            >
                                Dashboard
                            </Link>
                        )}
                    </nav>

                    {/* Main Content */}
                    <main className="flex flex-col items-center justify-center min-h-[80vh]">
                        <h1 
                            className="text-6xl font-bold mb-8" 
                            style={{ color: '#27A13C' }}
                        >
                            Welcome to Event Management System
                        </h1>
                        
                        <div className="max-w-3xl text-center">
                            <p className="text-gray-400 text-xl mb-8">
                                Plan, organize, and manage your events with ease
                            </p>
                            
                            <div className="flex gap-4 justify-center">
                                <Link
                                    href={route('login')}
                                    className="px-8 py-3 rounded-lg text-white text-lg transition"
                                    style={{ 
                                        backgroundColor: '#27A13C',
                                        hover: {
                                            backgroundColor: '#218A32'
                                        }
                                    }}
                                >
                                    Login
                                </Link>
                                <Link
                                    href={route('register')}
                                    className="px-8 py-3 rounded-lg text-white text-lg border-2 transition hover:bg-white/10"
                                    style={{ borderColor: '#27A13C' }}
                                >
                                    Register
                                </Link>
                            </div>
                        </div>
                    </main>

                    {/* Footer */}
                    <footer className="absolute bottom-0 w-full py-6 text-center text-gray-400">
                        <p>Event Management System v{laravelVersion} (PHP v{phpVersion})</p>
                    </footer>
                </div>
            </div>
        </>
    );
}

// resources/js/Pages/Welcome.vue
<script setup>
import { Head, Link } from '@inertiajs/vue3';

defineProps({
    canLogin: {
        type: Boolean,
    },
    canRegister: {
        type: Boolean,
    },
    laravelVersion: {
        type: String,
    },
    phpVersion: {
        type: String,
    },
});
</script>

<template>
    <Head title="Welcome" />

    <div class="relative sm:flex sm:justify-center sm:items-center min-h-screen bg-dots-darker bg-center bg-gray-100 dark:bg-dots-lighter dark:bg-gray-900 selection:bg-red-500 selection:text-white">
        <div v-if="canLogin" class="sm:fixed sm:top-0 sm:right-0 p-6 text-right">
            <Link v-if="$page.props.auth.user" :href="route('profile.edit')" class="font-semibold text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white focus:outline focus:outline-2 focus:rounded-sm focus:outline-red-500">
                Profile
            </Link>

            <template v-else>
                <Link :href="route('login')" class="font-semibold text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white focus:outline focus:outline-2 focus:rounded-sm focus:outline-red-500">
                    Log in
                </Link>

                <Link v-if="canRegister" :href="route('register')" class="ml-4 font-semibold text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white focus:outline focus:outline-2 focus:rounded-sm focus:outline-red-500">
                    Register
                </Link>
            </template>
        </div>

        <!-- Rest of your welcome page content -->
    </div>
</template>

<style>
/* Your existing styles */
</style>
